### ISSUE TITLE
请问thinknode跟thinkjs是什么区别呢？

### ISSUE THREAD

**Issue by geminiblue** [richenlin/thinknode#3]
https://thinkjs.org  这个是thinkjs的
然后看了看thinknode的文档，发现跟thinkjs有点相似

**Comment by RicherdLee** [comment]
最开始为了团队能够快速的从thinkphp转过来，我们参考了thinkjs的架构。
在随后的版本我们替换了ORM为waterline，同时也学习了koa中的一些优点，不断改进框架。
而近期在4.x的版本中，我们将ORM换为了我们自己的thinkorm。
thinkjs给我们很多的启发。无论thinkphp还是thinkjs都是非常优秀的框架
